
spring.application.name=SIS
spring.datasource.url=jdbc:mysql://localhost:3306/sis_db
spring.datasource.username=root
spring.datasource.password=akasha1807
spring.jpa.hibernate.ddl-auto=update


# JWT Configuration
app.jwtSecret=mySecretKeyForJwtTokenGenerationThatMustBeAtLeast32CharactersLong
app.jwtExpirationMs=86400000

# Swagger Configuration
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs

